Wzp 写了后端link.ts
SECourse2023/pink pull request #10
Opened 2023-04-24 12:01 UTC by ysghwzp

实现了 create(给5个参数)
list （给2个参数 from to，两个参数中可以有一个null）
get （根据id 返回link）
update （根据 id，改其余四个参数（可选），返回0/1表示是否成功）
delete （根据id删，返回0/1表示是否成功）

2023-04-24 12:24 UTC, thezzisu requested changes

2023-04-24 12:24 UTC, thezzisu commented on apps/server/src/controllers/link.ts
> +      config: {
删除所有的这样的config。不需要跳过验证。

2023-04-24 12:35 UTC, ysghwzp commented on apps/server/src/controllers/link.ts
> +      config: {
已经删了

2023-05-01 11:29 UTC, thezzisu approved these changes

2023-05-01 11:29 UTC, merged