pin.ts first
SECourse2023/pink pull request #12
Opened 2023-04-24 12:12 UTC by Github-Tree-0

New functions in controllers/pin.ts:
creat
list
get
update
delete

2023-04-24 12:22 UTC, thezzisu requested changes

2023-04-24 12:22 UTC, thezzisu commented on apps/server/src/controllers/pin.ts
> +            _id: Type.String(),
不应该在Create的时候传入_id，这个_id应该用nanoid生成

2023-04-24 12:22 UTC, thezzisu commented on apps/server/src/controllers/pin.ts
> +        _id: req.body._id,
这里使用registerDOID生成一下doid

2023-04-24 12:22 UTC, thezzisu commented on apps/server/src/controllers/pin.ts
> +        bypassAuth: true
这些route都不需要bypassAuth。删除本文件中所有这样的config

2023-04-24 12:33 UTC, Github-Tree-0 commented
fixed

2023-05-01 11:30 UTC, thezzisu approved these changes

2023-05-01 11:30 UTC, merged